### PR TITLE
Win

### PR DESCRIPTION
**Pull request by ocefpaf**
Needs https://github.com/conda-forge/libarchive-feedstock/pull/19 and is needed in https://github.com/conda-forge/conda-build-feedstock/pull/72.

### CODE REVIEW

**Comment by ocefpaf** [comment]
We need to decide on what to do for `vc9` support here. Abandon it or patch the code?

**Comment by bollwyvl** [comment]
@ocefpaf thanks for all the support on this one. What would I need to look into for vc9?

**Comment by ocefpaf** [comment]
@mingwandroid probably know best. Here is his comment about it:

https://github.com/conda-forge/conda-build-feedstock/pull/72#issuecomment-427449435

We do have `c99-to-c89` but we are missing `libxz` (maybe more?).

**Comment by bollwyvl** [comment]
Ah, fantastic :duck: s

Happy to help, but indeed probably a bit out of my ken.

**Comment by ocefpaf** [comment]
Also, see this comment:

https://github.com/AnacondaRecipes/libarchive-feedstock/blob/master/recipe/meta.yaml#L33-L35

Looks like there is a manual step on the AR side that we should emulate in `conda-forge` somehow :-/

**Comment by mingwandroid** [comment]
Well, it's just that my fork of c99-to-c89 isn't able to handle some of the constructs in this codebase, therefore I converted them by hand.

The original c99-to-c89 without my patches is useless for nearly everything! I fixed a tonne of bugs in c99-to-c89 but there's some more and actually it's a very dead project too.

**Comment by mingwandroid** [comment]
So all you need is the patches at: https://github.com/AnacondaRecipes/libarchive-feedstock/blob/master/recipe/meta.yaml#L14-L23

**Comment by ocefpaf** [comment]
Thanks @mingwandroid! But I think I got all of those so the issue here may be something different then :-/

**Pull request merged**
